// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkJX0YiuhAv4Tz3MxIORyfxSWY2UwOyA4',
    appId: '1:949774273802:web:48fb5371397091acdbfef3',
    messagingSenderId: '949774273802',
    projectId: 'fooddeliveryapp-d5278',
    authDomain: 'fooddeliveryapp-d5278.firebaseapp.com',
    databaseURL: 'https://fooddeliveryapp-d5278-default-rtdb.firebaseio.com',
    storageBucket: 'fooddeliveryapp-d5278.firebasestorage.app',
    measurementId: 'G-WRN09DMNE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtuJRoJhlxkw7eTHFD5v1nMlrAnLqxz5E',
    appId: '1:949774273802:android:7eb705268ada630adbfef3',
    messagingSenderId: '949774273802',
    projectId: 'fooddeliveryapp-d5278',
    databaseURL: 'https://fooddeliveryapp-d5278-default-rtdb.firebaseio.com',
    storageBucket: 'fooddeliveryapp-d5278.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQM0aDrkMx2oAXdn7VR3-WyGwUmYZLL0s',
    appId: '1:949774273802:ios:adffd820881f2319dbfef3',
    messagingSenderId: '949774273802',
    projectId: 'fooddeliveryapp-d5278',
    databaseURL: 'https://fooddeliveryapp-d5278-default-rtdb.firebaseio.com',
    storageBucket: 'fooddeliveryapp-d5278.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQM0aDrkMx2oAXdn7VR3-WyGwUmYZLL0s',
    appId: '1:949774273802:ios:adffd820881f2319dbfef3',
    messagingSenderId: '949774273802',
    projectId: 'fooddeliveryapp-d5278',
    databaseURL: 'https://fooddeliveryapp-d5278-default-rtdb.firebaseio.com',
    storageBucket: 'fooddeliveryapp-d5278.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkJX0YiuhAv4Tz3MxIORyfxSWY2UwOyA4',
    appId: '1:949774273802:web:3ed46d0959cfb4b2dbfef3',
    messagingSenderId: '949774273802',
    projectId: 'fooddeliveryapp-d5278',
    authDomain: 'fooddeliveryapp-d5278.firebaseapp.com',
    databaseURL: 'https://fooddeliveryapp-d5278-default-rtdb.firebaseio.com',
    storageBucket: 'fooddeliveryapp-d5278.firebasestorage.app',
    measurementId: 'G-W6CQRJNPEB',
  );
}